import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-Do-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} `}>
        <head>
          <link rel="icon" href="/test-nextjs/app/favicon.ico" />
        </head>
        <div className="relative min-h-screen min-w-screen flex justify-center items-center bg-accent flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
